@startuml
'https://plantuml.com/sequence-diagram

title Add inventory sequence diagram

actor Supplier as actorSupplier
actor Manager as actorManager
participant ":Inventory System" as InventorySystem
participant ":Stock" as classStock
participant ":Product" as classProduct

activate actorManager
activate InventorySystem

'-------------- START add stock ---------------
actorSupplier -> actorManager : shipment
activate actorSupplier

actorManager --> actorSupplier : receive shipment
deactivate actorSupplier

actorManager -> InventorySystem : 1 RequestAddStock


InventorySystem -> classProduct: 1.2 getAllProduct()
activate classProduct

classProduct --> InventorySystem: 1.3 return product
deactivate classProduct

InventorySystem  --> actorManager: 1.4 Response product

actorManager -> InventorySystem : 2 RequestSelectProduct
actorManager -> InventorySystem :  3 SaveAddStock

InventorySystem -> InventorySystem :  3.1 CalculateQtyStock


InventorySystem -> classStock: 3.2 updateQtyStock
activate classStock

deactivate classStock

InventorySystem  --> actorManager : 4 Response Add stock status
deactivate InventorySystem

deactivate actorManager

@enduml