@startuml
'https://plantuml.com/sequence-diagram

title Update inventory sequence diagram

actor Manager as actorManager
participant "Inventory System" as InventorySystem
participant "Stock" as classStock

'participant "Category" as classCategory

'actorManager -> InventorySystem: 1. RequestViewStock
'activate InventorySystem

'-------------- START add stock ---------------

actorManager -> InventorySystem : 1 RequestUpdateStock

InventorySystem -> classStock: 1.2 getQtyStock()
activate classStock

classStock --> InventorySystem: 1.3 return present qty stock
deactivate classStock


InventorySystem -> InventorySystem :  1.4 CalculateQtyStock


InventorySystem -> classStock: 1.5 updateQtyStock
activate classStock

classStock --> InventorySystem: 1.6 return new qty stock
deactivate classStock

InventorySystem  --> actorManager : 2 Display update stock status
deactivate InventorySystem


@enduml