@startuml
'example
title add product sequence diagram

actor Manager as actorManager
participant ":Inventory System" as InventorySystem
participant ":Product" as classProduct
participant ":Category" as classCategory

activate actorManager

actorManager -> InventorySystem: 1. requestAddProduct()
activate InventorySystem

InventorySystem -> classCategory: 1.1 getCategory(productData.categoryId)
activate classCategory

classCategory --> InventorySystem: 1.2 return category
deactivate classCategory

InventorySystem -> classProduct: 1.3 createProduct(productData)
activate classProduct


classProduct --> InventorySystem: 1.4 return create product
deactivate classProduct

InventorySystem --> actorManager: 2. response product
deactivate InventorySystem

deactivate actorManager

@enduml