@startuml
'example
title delete product sequence diagram

actor Manager as actorManager
participant ":Inventory System" as InventorySystem
participant ":Product" as classProduct

activate actorManager

actorManager -> InventorySystem: 1. RequestDeleteProduct
activate InventorySystem

InventorySystem -> classProduct: 1.1 deleteProduct(productId)
activate classProduct


classProduct --> InventorySystem: 1.2 return delete product status
deactivate classProduct

InventorySystem -> actorManager: 2. Response delete product status
deactivate InventorySystem

deactivate actorManager

@enduml