@startuml
'example
title View order sequence diagram

actor Manager as actorManager
participant "Inventory System" as InventorySystem
'participant "Inventory" as classInventory
participant "Order" as classOrder


actorManager -> InventorySystem: 1. RequestViewAllProduct
activate InventorySystem

'-------------- START view product ---------------
InventorySystem -> classOrder: 1.1 getAllCategory()
activate classOrder

classOrder --> InventorySystem: 1.2 return all category
deactivate classOrder


'-------------- END view product ---------------

InventorySystem --> actorManager : 2. Response products

deactivate InventorySystem


actorManager -> InventorySystem: 3. RequestViewCategory
activate InventorySystem

'-------------- START view product ---------------
InventorySystem -> classOrder: 3.1 getCategory(id)
activate classOrder

classOrder --> InventorySystem: 3.2 return category
deactivate classOrder


'-------------- END view product ---------------

InventorySystem --> actorManager : 4. Response product

deactivate InventorySystem

@enduml