@startuml
'example
title View order sequence diagram

actor Salesperson as actorSalesperson
participant "Inventory System" as InventorySystem
participant "Order" as classOrder

actorSalesperson -> InventorySystem: 1. RequestViewAllOrder
activate InventorySystem

InventorySystem -> classOrder: 1.1 getAllOrder()
activate classOrder

classOrder --> InventorySystem: 1.2 return all Order
deactivate classOrder


InventorySystem --> actorSalesperson : 2. Response orders
deactivate InventorySystem


opt
actorSalesperson -> InventorySystem: 3. RequestViewOrder
activate InventorySystem

InventorySystem -> classOrder: 3.1 getOrder(id)
activate classOrder

classOrder --> InventorySystem: 3.2 return order
deactivate classOrder


'-------------- END view product ---------------

InventorySystem --> actorSalesperson : 4. Response order

deactivate InventorySystem
end





@enduml