@startuml
'example
title View invoice sequence diagram

actor Salesperson as actorSalesperson
participant "Inventory System" as InventorySystem

participant "Invoice" as classInvoice

actorSalesperson -> InventorySystem: 1. RequestViewAllInvoice
activate InventorySystem

InventorySystem -> classInvoice: 1.1 getAllInvoice()
activate classInvoice

classInvoice --> InventorySystem: 1.2 return all invoice
deactivate classInvoice

InventorySystem --> actorSalesperson : 2. Response invoices

deactivate InventorySystem


opt
actorSalesperson -> InventorySystem: 3. RequestViewInvoice
activate InventorySystem

InventorySystem -> classInvoice: 3.1 getInvoice(id)
activate classInvoice

classInvoice --> InventorySystem: 3.2 return invoice
deactivate classInvoice

InventorySystem --> actorSalesperson : 4. Response invoice
deactivate InventorySystem
end


opt
actorSalesperson -> InventorySystem : 5. RequestPrintInvoice
activate InventorySystem

activate classInvoice
InventorySystem -> classInvoice : 5.1 printInvoice()

classInvoice -> classInvoice : 5.2  print invoice
deactivate classInvoice
deactivate InventorySystem

end

opt
actorSalesperson -> InventorySystem: 6. RequestEditInvoice
activate InventorySystem

InventorySystem -> classInvoice: 6.1 getEditInvoice(invoiceData)
activate classInvoice

classInvoice --> InventorySystem: 6.2 return invoice edit invoice
deactivate classInvoice

InventorySystem --> actorSalesperson : 6. Response Edit invoice status
deactivate InventorySystem
end


@enduml