@startuml
'example
title View invoice sequence diagram

actor Cashier as actorCashier
participant ":Inventory System" as InventorySystem

participant ":Invoice" as classInvoice

activate actorCashier

actorCashier -> InventorySystem: 1. requestViewAllInvoice()
activate InventorySystem

InventorySystem -> classInvoice: 1.1 getAllInvoice()
activate classInvoice

classInvoice --> InventorySystem: 1.2 return all invoice
deactivate classInvoice

InventorySystem --> actorCashier : 2. response invoices




opt
actorCashier -> InventorySystem: 3. RequestViewInvoice


InventorySystem -> classInvoice: 3.1 getInvoice(id)
activate classInvoice

classInvoice --> InventorySystem: 3.2 return invoice
deactivate classInvoice

InventorySystem --> actorCashier : 4. response invoice

end


opt
actorCashier -> InventorySystem : 5. requestPrintInvoice()


activate classInvoice
InventorySystem -> classInvoice : 5.1 printInvoice()

classInvoice -> classInvoice : 5.2  printInvoice()

end
deactivate classInvoice

opt
actorCashier -> InventorySystem: 6. requestEditInvoice()


InventorySystem -> classInvoice: 6.1 getEditInvoice(invoiceData)
activate classInvoice

classInvoice --> InventorySystem: 6.2 return invoice edit invoice
deactivate classInvoice

InventorySystem --> actorCashier : 7. response edit invoice status
end
deactivate InventorySystem


@enduml