@startuml
'example
title Create Sell sequence diagram

actor Salesperson as actorSalesperson
participant "Inventory System" as InventorySystem
participant "Sale" as classSell

participant "Receipt" as classReceipt


actorSalesperson -> InventorySystem: 1. RequestCreateSell
activate InventorySystem

InventorySystem -> classSell: 1.1 createSell()
activate classSell

classSell -> classReceipt : 1.2 system create receipt

activate classReceipt
classReceipt -> classReceipt : 1.3 print receipt


classReceipt --> InventorySystem: 1.4 return receipt
deactivate classReceipt

classSell --> InventorySystem: 1.5 return create sell
deactivate classSell

InventorySystem --> actorSalesperson : 2. Response create sell status

deactivate InventorySystem




@enduml