@startuml
'example
title View Receipt sequence diagram

actor Cashier as actorCashier
participant ":Inventory System" as InventorySystem
participant ":Receipt" as classReceipt

activate actorCashier

actorCashier -> InventorySystem: 1. RequestViewAllReceipt
activate InventorySystem

'-------------- START view product ---------------
InventorySystem -> classReceipt: 1.1 getAllReceipt()
activate classReceipt

classReceipt --> InventorySystem: 1.2 return all Receipt
deactivate classReceipt

InventorySystem --> actorCashier : 2. Response Receipts



opt
actorCashier -> InventorySystem: 3. RequestViewReceipt

InventorySystem -> classReceipt: 3.1 getReceipt(id)
activate classReceipt

classReceipt --> InventorySystem: 3.2 return Receipt
deactivate classReceipt


'-------------- END view product ---------------

InventorySystem --> actorCashier : 4. Response Receipt


end


opt
actorCashier -> InventorySystem : 5. Request Print Receipt


InventorySystem -> classReceipt : 5.1 printReceipt()

activate classReceipt
classReceipt -> classReceipt : 5.2  print Receipt


end
deactivate InventorySystem




@enduml