@startuml
'example
title View Sell report sequence diagram

actor "Financial" as actorFinancial
actor "Manager" as actorManager
participant ":Inventory System" as InventorySystem
participant ":Sell report" as usecaseSellReport

activate actorManager

activate InventorySystem
actorManager -> InventorySystem: 1. RequestViewAllSellReport

'-------------- START view product ---------------
InventorySystem -> usecaseSellReport: 1.1 getAllSellReport()
activate usecaseSellReport

usecaseSellReport --> InventorySystem: 1.2 return all SellReport
deactivate usecaseSellReport

InventorySystem --> actorManager : 2. Response SellReport



opt
actorManager -> InventorySystem: 3. RequestViewSellReport


InventorySystem -> usecaseSellReport: 3.1 getSellReport(id)
activate usecaseSellReport

usecaseSellReport --> InventorySystem: 3.2 return SellReport
deactivate usecaseSellReport


'-------------- END view product ---------------

InventorySystem --> actorManager : 4. Response SellReport

end


opt
actorManager -> InventorySystem : 5. Request Print sell report



InventorySystem -> usecaseSellReport : 5.1 printSellReport()
activate usecaseSellReport

usecaseSellReport -> usecaseSellReport : 5.2  print sell report


end
deactivate usecaseSellReport

deactivate actorManager



actorFinancial -> InventorySystem: 6. RequestViewWeeklySellReport
activate actorFinancial

InventorySystem -> usecaseSellReport: 6.1 getWeeklySellReport()
activate usecaseSellReport

usecaseSellReport --> InventorySystem: 6.2 return sell report
deactivate usecaseSellReport

InventorySystem --> actorFinancial : 7. Response sell report
deactivate actorManager

deactivate InventorySystem
deactivate actorFinancial


@enduml