@startuml
'example
title View Sell report sequence diagram

actor "Financial" as actorFinancial
actor "Manager" as actorManager
participant ":Inventory System" as InventorySystem
participant ":Sell report" as usecaseSellReport

activate actorManager

activate InventorySystem
actorManager -> InventorySystem: 1. requestViewAllSellReport()

'-------------- START view product ---------------
InventorySystem -> usecaseSellReport: 1.1 getAllSellReport()
activate usecaseSellReport

usecaseSellReport --> InventorySystem: 1.2 return all SellReport
deactivate usecaseSellReport

InventorySystem --> actorManager : 2. response SellReport



opt
actorManager -> InventorySystem: 3. requestViewSellReport()


InventorySystem -> usecaseSellReport: 3.1 getSellReport(id)
activate usecaseSellReport

usecaseSellReport --> InventorySystem: 3.2 return SellReport
deactivate usecaseSellReport


'-------------- END view product ---------------

InventorySystem --> actorManager : 4. response sell report

end


opt
actorManager -> InventorySystem : 5. request print sell report



InventorySystem -> usecaseSellReport : 5.1 printSellReport()
activate usecaseSellReport

usecaseSellReport -> usecaseSellReport : 5.2  printSellReport()


end
deactivate usecaseSellReport

deactivate actorManager



actorFinancial -> InventorySystem: 6. requestViewWeeklySellReport
activate actorFinancial

InventorySystem -> usecaseSellReport: 6.1 getWeeklySellReport()
activate usecaseSellReport

usecaseSellReport --> InventorySystem: 6.2 return sell report
deactivate usecaseSellReport

InventorySystem --> actorFinancial : 7. response sell report
deactivate actorManager

deactivate InventorySystem
deactivate actorFinancial


@enduml