@startuml
'example
title View Sell report sequence diagram

actor Manager as actorManager
participant ":Inventory System" as InventorySystem
participant ":Sell report" as classSellReport


actorManager -> InventorySystem: 1. RequestCreateSellReport
activate actorManager
activate InventorySystem

'-------------- START view product ---------------
InventorySystem -> classSellReport: 1.1 createSellReport(SellReportData)
activate classSellReport

classSellReport --> InventorySystem: 1.2 return create SellReport status
deactivate classSellReport

InventorySystem --> actorManager : 2. Response Create SellReport status


loop every month
actorManager -> InventorySystem : create monthly sell report
InventorySystem -> classSellReport : createSellReport
activate classSellReport
classSellReport --> InventorySystem : response create sell report
deactivate classSellReport

InventorySystem -> actorManager : response create monthly sell report
end loop

deactivate InventorySystem
deactivate actorManager
@enduml