@startuml
'example
title View ProductOrderList sequence diagram


actor Supplier as actorSupplier
actor CEO as actorCEO
actor Manager as actorManager
participant "Inventory System" as InventorySystem
'participant "Stock" as classInventory
participant "Product Order List" as classProductOrderList



activate InventorySystem
actorManager -> InventorySystem: 1. RequestViewAllProductOrderList

'-------------- START view product ---------------
InventorySystem -> classProductOrderList: 1.1 getAllProductOrderList()
activate classProductOrderList

classProductOrderList --> InventorySystem: 1.2 return all ProductOrderList
deactivate classProductOrderList

InventorySystem --> actorManager : 2. Response ProductOrderList

deactivate InventorySystem


opt
actorManager -> InventorySystem: 3. RequestViewProductOrderList
activate InventorySystem

InventorySystem -> classProductOrderList: 3.1 getProductOrderList(id)
activate classProductOrderList

classProductOrderList --> InventorySystem: 3.2 return ProductOrderList
deactivate classProductOrderList


'-------------- END view product ---------------

InventorySystem --> actorManager : 4. Response product order list

deactivate InventorySystem
end

actorCEO -> InventorySystem : 5. RequestPendingProductOrderList
activate InventorySystem

InventorySystem -> classProductOrderList : 5.1 getPendingProductOrderList
activate classProductOrderList

classProductOrderList --> InventorySystem : 5.2 return pending product order list
deactivate classProductOrderList

InventorySystem --> actorCEO : 6 Response pending product order list
deactivate InventorySystem
opt

actorCEO -> InventorySystem : 7. RequestConfirmProductOrderList
activate InventorySystem

InventorySystem -> classProductOrderList : 7.1 confirmProductOrderList
activate classProductOrderList

classProductOrderList --> InventorySystem : 7.2 return confirm status
deactivate classProductOrderList

InventorySystem --> actorCEO : 8. Response confirm product order list status
deactivate InventorySystem

end

actorManager -> InventorySystem : 9. RequestConfirmedProductOrderList
activate InventorySystem

InventorySystem -> classProductOrderList : 9.1 getConfirmedProductOrderList
classProductOrderList --> InventorySystem : 9.2 return confirmed product order list

InventorySystem --> actorManager : 10. Response confirmed product order list
deactivate InventorySystem

actorManager -> actorSupplier : 11. Send product order list to supplier
actorSupplier --> actorManager : 12. shipment product following product order list to supplier

@enduml