@startuml
'example
title View ProductOrderList sequence diagram

actor Manager as actorManager
participant "Inventory System" as InventorySystem
participant "ProductOrderList" as classProductOrderList
participant "Stock" as classStock
participant "Product" as classProduct



actorManager -> InventorySystem: 1. RequestCreateProductOrderList
activate InventorySystem

InventorySystem -> classProduct : 1.1 getProduct
activate classProduct

classProduct --> InventorySystem : 1.2 return product
deactivate classProduct

InventorySystem --> actorManager : 2. Response product

actorManager --> InventorySystem : 3. Request Check Stock


InventorySystem -> classStock: 1.3 checkStock
activate classStock

classStock --> InventorySystem: 1.4 return stock
deactivate classStock

InventorySystem --> actorManager : 1.5 response stock

InventorySystem -> classProductOrderList: 1.5 createProductOrderList
activate classProductOrderList

classProductOrderList --> InventorySystem: 1.6 return create product order list status
deactivate classProductOrderList

InventorySystem --> actorManager : 2. Response Create ProductOrderList status
deactivate InventorySystem




@enduml