@startuml
'https://plantuml.com/usecase-diagram

skinparam sequence {
    ParticipantFontName Thai
    ParticipantFontSize 16
    ActorFontSize 16
    ActorFontName Thai
}
'skinparam linetype polyline
' skinparam linetype ortho

skinparam Participant{
    FontColor #efefef
    BorderColor #c0c0c0
}
skinparam Sequence{
    ParticipantBorderThickness .5
    LifeLineBorderColor #8a8a8a
}

' =================== Customer ===================
' role - ผู้ที่เข้ามาเพื่อซื้อสินค้าภายในบริษัท
' duty - ทำให้เกิดการซื้อขายสินค้า
actor Customer as actorCustomer
note bottom of actorCustomer : ลูกค้าผู้ที่เข้ามาซื้อสินค้าภายในบริษัท
' =================== Manager ===================
' role - เจ้าหน้าที่ ที่จัดการสินค้า ให้คงคลังสินค้าอยู่เสมอ
' duty - บริหารจัดการ stock สินค้า ทั้งการจำหน่ายออก และการรับสินค้ารวมถึงการ
' ออกใบสั่งของ การเช็คสินค้าและการทำรายงานต่างๆ
actor Manager as actorManager
note top of actorManager : เจ้าหน้าที่ ที่จัดการสินค้า
' =================== Supplier ===================
' role - เป็นบริษัทคู่ค้าที่จำหน่ายสินค้าหรือวัตถุดิบให้กับบริษัท
' duty - ขายและจัดส่งสินค้าตามใบสั่งของ
actor Supplier as actorSupplier
note right of actorSupplier : เป็นบริษัทคู่ค้าที่จำหน่ายสินค้า
' =================== Financial ===================
' role - เป็นฝ่ายดูแลบัญชีและการเงินของบริษัท
' duty - รับข้อมูลการซื้อและขายสินค้า
actor Financial as actorFinancial
note top of actorFinancial : เป็นฝ่ายดูแลบัญชี

actor Cashier as actorCashier
note top of actorCashier : พนักงานขาย

actor CEO as actorCEO
note bottom of actorCEO : ผู้บริหารระดับสูง


' =================== Stock System ===================
rectangle "ระบบจัดการสินค้าคงคลัง" as stockSystem {

    ' ================ Selling ================
    ' กระบวนการขายสินค้า
    usecase (Sell) as (usecaseSell)
    '    note bottom of usecaseSell : กระบวนการขายสินค้า

    ' ================ Reporting ================
    '   การทำรายงาน
    usecase (Sell Report) as (usecaseSellReport)
    usecase (Create Sell Report) as (usecaseCreateSellReport)
    usecase (Edit Sell Report) as (usecaseEditSellReport)
    usecase (Delete Sell Report) as (usecaseDeleteSellReport)

    '    การขายสินค้า
    usecase (Sell product) as (usecaseSellProduct)
    '    การตรวจสอบยอดสินค้า

    '    ออกใบเสร็จ
    usecase (Manage Receipt) as (usecaseReceipt)
    usecase (View Receipt) as (usecaseViewReceipt)
    usecase (Print receipt) as (usecasePrintReceipt)
    usecase (Edit receipt) as (usecaseEditReceipt)
    usecase (Create receipt) as (usecaseCreateReceipt)

    ' ================ Invoice ================
    usecase (Manage Invoice) as (usecaseInvoice)
    usecase (View Invoice) as (usecaseViewInvoice)
    usecase (Create Invoice) as (usecaseCreateInvoice)
    usecase (Edit Invoice) as (usecaseEditInvoice)
    usecase (Print Invoice) as (usecasePrintInvoice)

    ' ================ Ordering ================
    '    การสั่งซื้อสินค้า

    usecase (Order) as (usecaseOrder)
    '    note bottom of usecaseOrder : การสั่งซื้อสินค้า
    usecase (Edit Order) as (usecaseEditOrder)
    usecase (Cancel Order) as (usecaseDeleteOrder)

    usecase (stock order from supplier) as (usecaseStockOrderFromSupplier)
    usecase (Create stock order) as (usecaseCreateStockOrder)
    usecase (Confirm stock order) as (usecaseConfirmStockOrder)

    ' ================ Stock ================
    usecase (Manage stock) as (usecaseStock)
    usecase (Check Stock) as (usecaseCheckStock)
    usecase (Add stock) as (usecaseAddStock)
    usecase (Update stock) as (usecaseUpdateStock)

    ' ================ Product ================
    usecase (Manage product) as (usecaseProduct)
    usecase (View product) as (usecaseViewProduct)
    usecase (Add product) as (usecaseAddProduct)
    usecase (Edit product) as (usecaseUpdateProduct)
    usecase (Delete product) as (usecaseDeleteProduct)
    usecase (Select product) as (usecaseSelectProduct)

    usecase (Promotion) as (usecasePromotion)

    ' ================ Category ================
    usecase (Manage category) as (usecaseCategory)
    usecase (View category) as (usecaseViewCategory)
    usecase (Add category) as (usecaseAddCategory)
    usecase (Edit category) as (usecaseUpdateCategory)
    usecase (Delete category) as (usecaseDeleteCategory)


    ' ================ Shipment ================
    usecase (Shipment) as (usecaseShipment)


    '===========================================================
    ' ===                  Associate Flow                    ===
    '===========================================================


    ' ================ Product ================
    actorManager -- (usecaseProduct)
    (usecaseProduct) <.. (usecaseAddProduct)  : <<extends>>
    (usecaseUpdateProduct) ..> (usecaseProduct) : <<extends>>
    (usecaseProduct) <.. (usecaseDeleteProduct)  : <<extends>>
    (usecaseSelectProduct) ..> (usecaseProduct) : <<extends>>
    (usecaseProduct) <.. (usecaseViewProduct) : <<extends>>

    (usecaseProduct) ..> (usecaseViewCategory) : <<include>>
    (usecaseProduct) <.. (usecasePromotion) : <<extends>>


    ' ================ Category ================
    actorManager -- (usecaseCategory)
    (usecaseCategory) <.. (usecaseAddCategory)  : <<extends>>
    (usecaseUpdateCategory) ..> (usecaseCategory) : <<extends>>
    (usecaseCategory) <.. (usecaseDeleteCategory)  : <<extends>>
    (usecaseViewCategory)  ..> (usecaseCategory) : <<extends>>


    ' ================ Stock ================
    actorSupplier -down- (usecaseShipment)
    (usecaseStock) - actorManager

    (usecaseAddStock) ..> (usecaseStock) : <<extends>>
    (usecaseAddStock) ..> (usecaseViewProduct) : <<include>>
    (usecaseUpdateStock) ..> (usecaseStock) : <<extends>>
    (usecaseStock) <.. (usecaseCheckStock) : <<extends>>

    ' ================ Sell ================
    (usecaseSellProduct) ..> (usecaseSell) : <<extends>>

    (usecaseSellProduct)  ..> (usecaseCreateReceipt) : <<include>>
    (usecaseSell)  ..> (usecaseOrder) : <<include>>

    '   ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการขาย
    actorCashier - (usecaseSell)

    '   การลงรับสินค้า เป็นส่วนหนึ่งของกระบวนการสั่งซื้อสินค้า
    (usecaseOrder) ..> (usecaseSelectProduct) : <<include>>
    (usecaseViewProduct) <.. (usecaseOrder) : <<include>>

    '   การปรับปรุงยอดสินค้า เป็นส่วนหนึ่งของกระบวนการสั่งซื้อสินค้า
    (usecaseCheckStock) <.. (usecaseOrder) : <<include>>

    ' ================ Order ================
    (usecaseOrder) <.. (usecaseDeleteOrder) : <<extends>>
    (usecaseEditOrder) ..> (usecaseOrder) : <<extends>>

    (usecaseDeleteOrder) ..> (usecaseUpdateStock) : <<include>>
    (usecaseCreateInvoice) <.. (usecaseOrder) : <<include>>

    ' ===  ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการสั่งซื้อสินค้า ===
    actorCashier -- (usecaseOrder)
    (usecaseOrder) -- actorCustomer

    ' ================ Invoice ================
    (usecaseInvoice) <.. (usecaseViewInvoice) : <<extends>>
    (usecaseInvoice)  <..   (usecaseCreateInvoice): <<extends>>
    (usecaseEditInvoice) ..> (usecaseInvoice) : <<extends>>

    (usecaseCreateInvoice) ..> (usecasePrintInvoice) : <<include>>
    (usecasePrintInvoice) ..> (usecaseViewInvoice) : <<include>>

     (usecaseInvoice) -- actorCashier

    ' ================ Receipt ================
    (usecaseCreateReceipt) .up.> (usecaseReceipt) : <<extends>>
    (usecaseViewReceipt) .> (usecaseReceipt) : <<extends>>
    (usecaseEditReceipt) ...> (usecaseReceipt) : <<extends>>
    (usecaseCreateReceipt) .up.> (usecasePrintReceipt) : <<include>>
    (usecaseViewReceipt)  <..   (usecasePrintReceipt): <<include>>

    (usecaseReceipt) -- actorCashier

    ' ===  ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการสออกรายงาน ===
    actorManager -- (usecaseSellReport)
    actorFinancial -right- (usecaseSellReport)


    ' ================ Reporting ================
    '   การทำรายงาน

    (usecaseSellReport) ..> (usecaseViewReceipt)    : <<include>>
    (usecaseCheckStock)  <.. (usecaseSellReport)  : <<include>>

    (usecaseCreateSellReport) ..>  (usecaseSellReport)   : <<extends>>
    (usecaseSellReport)   <.. (usecaseEditSellReport)   : <<extends>>
    (usecaseDeleteSellReport) ..>  (usecaseSellReport)   : <<extends>>

    (usecaseViewProduct) <... (usecaseCreateStockOrder) : <<include>>
    (usecaseConfirmStockOrder) ..> (usecaseCreateStockOrder) : <<extends>>
    (usecaseStockOrderFromSupplier) ...> (usecaseConfirmStockOrder)  : <<extend>>
   
    actorSupplier -- (usecaseStockOrderFromSupplier)
    actorCEO -- (usecaseConfirmStockOrder)
     (usecaseCreateStockOrder) -- actorManager



}

@enduml