@startuml
'https://plantuml.com/usecase-diagram
left to right direction

skinparam sequence {
    ParticipantFontName Thai
    ParticipantFontSize 16
    ActorFontSize 16
    ActorFontName Thai
}
'skinparam linetype polyline
' skinparam linetype ortho

skinparam Participant{
    FontColor #efefef
    BorderColor #c0c0c0
}
skinparam Sequence{
    ParticipantBorderThickness .5
    LifeLineBorderColor #8a8a8a
}

' =================== Manager ===================
' role - เจ้าหน้าที่ ที่จัดการสินค้า ให้คงคลังสินค้าอยู่เสมอ
' duty - บริหารจัดการ stock สินค้า ทั้งการจำหน่ายออก และการรับสินค้ารวมถึงการ
' ออกใบสั่งของ การเช็คสินค้าและการทำรายงานต่างๆ
actor Manager as actorManager
note top of actorManager : เจ้าหน้าที่ ที่จัดการสินค้า
' =================== Supplier ===================
' role - เป็นบริษัทคู่ค้าที่จำหน่ายสินค้าหรือวัตถุดิบให้กับบริษัท
' duty - ขายและจัดส่งสินค้าตามใบสั่งของ
actor Supplier as actorSupplier
note right of actorSupplier : เป็นบริษัทคู่ค้าที่จำหน่ายสินค้า

actor CEO as actorCEO
note bottom of actorCEO : ผู้บริหารระดับสูง


' =================== Stock System ===================
rectangle "จัดการคำสั่งซื้อสินค้าจาก Supllier " as manageOrderList {


    ' ================ Ordering ================
    '    การสั่งซื้อสินค้า

    usecase (Order product from supplier) as (usecaseOrderProductFromSupplier)
    usecase (Create product order list) as (usecaseCreateProductOrderList)
    usecase (confirm product order list) as (usecaseConfirmOrderList)

    actorManager -- (usecaseCreateProductOrderList)

    ' ================ Product ================

    usecase (View product) as (usecaseViewProduct)

    ' ================ Shipment ================
    usecase (Shipment) as (usecaseShipment)

    '===========================================================
    ' ===                  Associate Flow                    ===
    '===========================================================

    ' ================ Reporting ================
    '   การทำรายงาน

    (usecaseViewProduct) <... (usecaseCreateProductOrderList) : <<include>>
    (usecaseConfirmOrderList) ..> (usecaseCreateProductOrderList) : <<extends>>
    (usecaseOrderProductFromSupplier) ...> (usecaseConfirmOrderList)  : <<extend>>


    actorSupplier -- (usecaseOrderProductFromSupplier)
    actorCEO -- (usecaseConfirmOrderList)




}

@enduml