@startuml
'https://plantuml.com/sequence-diagram

class Product {
- id
- name
- desc
- brand

 + getProduct()
 + createProduct()
 + updateProduct()
 + deleteProduct()
}

class Category {
    - id
    - name
    - desc
}

class Stock {
    - id
    - qty
    - importDate
    - productId
}

class Receipt {
    - id
    - date
    - orderId
}

class Invoice {
    - id
    - productId
    - qty
}

class Order {
    - id
    - qty
    - productId
}

Product "1" -- "0..*" Category
Product "1" -- "0..*" Stock
Product "1..*" <|-- "1" Invoice




@enduml