@startuml
'https://plantuml.com/sequence-diagram

skinparam linetype polyline
'skinparam linetype ortho

skinparam Arrow{
    Thickness .6
}
skinparam Participant{
    FontColor #efefef
    BorderColor #c0c0c0
}
skinparam Sequence{
    ParticipantBorderThickness .5
    LifeLineBorderColor #8a8a8a
}

' =================== Customer ===================
' role - ผู้ที่เข้ามาเพื่อซื้อสินค้าภายในบริษัท
' duty - ทำให้เกิดการซื้อขายสินค้า
actor Customer as actorCustomer
note bottom of actorCustomer : ลูกค้าผู้ที่เข้ามาซื้อสินค้าภายในบริษัท
' =================== Manager ===================
' role - เจ้าหน้าที่ ที่จัดการสินค้า ให้คงคลังสินค้าอยู่เสมอ
' duty - บริหารจัดการ stock สินค้า ทั้งการจำหน่ายออก และการรับสินค้ารวมถึงการ
' ออกใบสั่งของ การเช็คสินค้าและการทำรายงานต่างๆ
actor Manager as actorManager
note top of actorManager : เจ้าหน้าที่ ที่จัดการสินค้า
' =================== Supplier ===================
' role - เป็นบริษัทคู่ค้าที่จำหน่ายสินค้าหรือวัตถุดิบให้กับบริษัท
' duty - ขายและจัดส่งสินค้าตามใบสั่งของ
actor Supplier as actorSupplier
note left of actorSupplier : เป็นบริษัทคู่ค้าที่จำหน่ายสินค้า
' =================== Financial ===================
' role - เป็นฝ่ายดูแลบัญชีและการเงินของบริษัท
' duty - รับข้อมูลการซื้อและขายสินค้า
actor Financial as actorFinancial
note top of actorFinancial : เป็นฝ่ายดูแลบัญชี

' =================== Stock System ===================
rectangle "Stock system" as stockSystem {

    ' ================ Selling ================
    ' กระบวนการขายสินค้า
    usecase (Sell) as (usecaseSell)
    note bottom of usecaseSell : กระบวนการขายสินค้า


    '    การขายสินค้า
    usecase (Sell product) as (usecaseSellProduct)
    '    การตรวจสอบยอดสินค้า

    '    ออกใบเสร็จ
    usecase (Manage Receipt) as (usecaseReceipt)
    usecase (View Receipt) as (usecaseViewReceipt)
    usecase (Print receipt) as (usecasePrintReceipt)
    usecase (Edit receipt) as (usecaseEditReceipt)
    usecase (Create receipt) as (usecaseCreateReceipt)

    ' ================ Ordering ================
    '    การสั่งซื้อสินค้า

    usecase (Order) as (usecaseOrder)
    note bottom of usecaseOrder : การสั่งซื้อสินค้า
    usecase (Edit Order) as (usecaseEditOrder)
    usecase (Delete Order) as (usecaseDeleteOrder)

    '    การลงรับสินค้า

    ' ================ Reporting ================
    '   การทำรายงาน
    usecase (Sell Report) as (usecaseSellReport)


    ' ================ Product ================
    '    การสั่งซื้อสินค้า
    usecase (View product) as (usecaseProduct)

    usecase (Add product) as (usecaseAddProduct)
    usecase (update product) as (usecaseUpdateProduct)
    usecase (Delete product) as (usecaseDeleteProduct)

    usecase (Pick up product) as (usecasePickUpProduct)

    ' ================ Stock ================
    usecase (Inventory) as (usecaseInventory)
    usecase (Check Stock) as (usecaseCheckStock)
    usecase (Add stock) as (usecaseAddStock)
    usecase (Update stock) as (usecaseUpdateStock)

    ' ================ Invoice ================
    usecase (Manage Invoice) as (usecaseInvoice)
    usecase (View Invoice) as (usecaseViewInvoice)
    usecase (Create Invoice) as (usecaseCreateInvoice)
    usecase (Edit Invoice) as (usecaseEditInvoice)
    usecase (Print Invoice) as (usecasePrintInvoice)

    ' ================ Shipment ================
    usecase (Shipment) as (usecaseShipment)




    '    ===================== Associate Flow =====================

    '    ================ actor - usecase Flow ================
    '   ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการขาย
    actorManager -- (usecaseSell)

    ' ===  ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการสั่งซื้อสินค้า ===
    actorManager -up- (usecaseOrder)
    (usecaseOrder) -- actorCustomer

    ' ===  ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการสออกรายงาน ===
    actorManager --- (usecaseSellReport)
    actorFinancial -up- (usecaseSellReport)

    actorManager - (usecaseInventory)
    actorManager -- (usecaseProduct)

    actorSupplier -down- (usecaseShipment)

    '================ usecase - usecase Flow ================


    (usecaseProduct) <.. (usecaseAddProduct)  : <<extends>>
    (usecaseUpdateProduct) ..> (usecaseProduct) : <<extends>>
    (usecaseProduct) <.. (usecaseDeleteProduct)  : <<extends>>
    (usecasePickUpProduct) ..> (usecaseProduct) : <<extends>>

    ' ================ Stock ================
    (usecaseAddStock) ..> (usecaseCheckStock) : <<extends>>
    (usecaseAddStock) ..> (usecaseProduct) : <<include>>

    (usecaseUpdateStock) ..> (usecaseInventory) : <<extends>>

    (usecaseInventory) <.. (usecaseCheckStock) : <<extends>>

    ' ================ Sell ================
    (usecaseSellProduct) ..> (usecaseSell) : <<extends>>
    (usecaseCheckStock) <.. (usecaseSell)    : <<include>>

    (usecaseSellProduct)  ..> (usecaseCreateReceipt) : <<include>>


    '   การลงรับสินค้า เป็นส่วนหนึ่งของกระบวนการสั่งซื้อสินค้า
    (usecaseOrder) ..> (usecasePickUpProduct) : <<include>>

    '   การปรับปรุงยอดสินค้า เป็นส่วนหนึ่งของกระบวนการสั่งซื้อสินค้า
    (usecaseCheckStock) <.. (usecaseOrder) : <<include>>

    ' ================ Order ================
    (usecaseOrder) <.. (usecaseDeleteOrder) : <<extends>>
    (usecaseEditOrder) ..> (usecaseOrder) : <<extends>>
    (usecaseEditOrder) ..> (usecaseUpdateStock) : <<include>>
    (usecaseCreateInvoice) <.. (usecaseOrder) : <<include>>

    ' ================ Invoice ================
    (usecaseInvoice) <.. (usecaseViewInvoice) : <<extends>>
    (usecaseInvoice)  <..   (usecaseCreateInvoice): <<extends>>
    (usecaseEditInvoice) ..> (usecaseInvoice) : <<extends>>

    (usecaseCreateInvoice) ..> (usecasePrintInvoice) : <<uses>>
    (usecasePrintInvoice) ..> (usecaseViewInvoice) : <<uses>>

    ' ================ Receipt ================
    (usecaseCreateReceipt) .up.> (usecaseReceipt) : <<extends>>
    (usecaseViewReceipt) ..> (usecaseReceipt) : <<extends>>
    (usecaseEditReceipt) ..> (usecaseReceipt) : <<extends>>

    (usecaseCreateReceipt) .up.> (usecasePrintReceipt) : <<uses>>
    (usecaseViewReceipt)  <..   (usecasePrintReceipt): <<uses>>

    ' ================ Reporting ================
    '   การทำรายงาน

    (usecaseSell) <..  (usecaseSellReport)   : <<include>>
    (usecaseCheckStock) <..  (usecaseSellReport)   : <<include>>

    ' ================ Shipment ================

}

@enduml