@startuml
'https://plantuml.com/sequence-diagram
'!theme toy
skinparam sequence {
'ArrowColor DeepSkyBlue
'ActorBorderColor DeepSkyBlue
'LifeLineBorderColor blue
'LifeLineBackgroundColor #A9DCDF

'ParticipantBorderColor DeepSkyBlue
'ParticipantBackgroundColor DodgerBlue
ParticipantFontName Thai
ParticipantFontSize 16
'ParticipantFontColor #A9DCDF

'ActorBackgroundColor black
ActorFontColor black
ActorFontSize 16
ActorFontName Thai
}


'skinparam linetype polyline
'skinparam linetype ortho

skinparam Arrow{
    Thickness .6
}
skinparam Participant{
    FontColor #efefef
    BorderColor #c0c0c0
}
skinparam Sequence{
    ParticipantBorderThickness .5
    LifeLineBorderColor #8a8a8a
}

' =================== Customer ===================
' role - ผู้ที่เข้ามาเพื่อซื้อสินค้าภายในบริษัท
' duty - ทำให้เกิดการซื้อขายสินค้า
actor Customer as actorCustomer
note bottom of actorCustomer : ลูกค้าผู้ที่เข้ามาซื้อสินค้าภายในบริษัท
' =================== Manager ===================
' role - เจ้าหน้าที่ ที่จัดการสินค้า ให้คงคลังสินค้าอยู่เสมอ
' duty - บริหารจัดการ stock สินค้า ทั้งการจำหน่ายออก และการรับสินค้ารวมถึงการ
' ออกใบสั่งของ การเช็คสินค้าและการทำรายงานต่างๆ
actor Manager as actorManager
note top of actorManager : เจ้าหน้าที่ ที่จัดการสินค้า
' =================== Supplier ===================
' role - เป็นบริษัทคู่ค้าที่จำหน่ายสินค้าหรือวัตถุดิบให้กับบริษัท
' duty - ขายและจัดส่งสินค้าตามใบสั่งของ
actor Supplier as actorSupplier
note left of actorSupplier : เป็นบริษัทคู่ค้าที่จำหน่ายสินค้า
' =================== Financial ===================
' role - เป็นฝ่ายดูแลบัญชีและการเงินของบริษัท
' duty - รับข้อมูลการซื้อและขายสินค้า
actor Financial as actorFinancial
note top of actorFinancial : เป็นฝ่ายดูแลบัญชี

actor Salesperson as actorSalesperson
note top of actorSalesperson : พนักงานขาย

actor CEO as actorCEO
note top of actorCEO : ผู้บริหารระดับสูง


' =================== Stock System ===================
rectangle "Stock system" as stockSystem {

    ' ================ Selling ================
    ' กระบวนการขายสินค้า
    usecase (Sell) as (usecaseSell)
    '    note bottom of usecaseSell : กระบวนการขายสินค้า

    ' ================ Reporting ================
    '   การทำรายงาน
    usecase (Sell Report) as (usecaseSellReport)
    usecase (List product for stock detail) as (usecaseListProductForStock)

    '    การขายสินค้า
    usecase (Sell product) as (usecaseSellProduct)
    '    การตรวจสอบยอดสินค้า

    '    ออกใบเสร็จ
    usecase (Manage Receipt) as (usecaseReceipt)
    usecase (View Receipt) as (usecaseViewReceipt)
    usecase (Print receipt) as (usecasePrintReceipt)
    usecase (Edit receipt) as (usecaseEditReceipt)
    usecase (Create receipt) as (usecaseCreateReceipt)

    ' ================ Ordering ================
    '    การสั่งซื้อสินค้า

    usecase (Order) as (usecaseOrder)
    '    note bottom of usecaseOrder : การสั่งซื้อสินค้า
    usecase (Edit Order) as (usecaseEditOrder)
    usecase (Cancel Order) as (usecaseDeleteOrder)

    usecase (Order product from supplier) as (usecaseOrderProductFromSupplier)

    '    การลงรับสินค้า

    ' ================ Invoice ================
    usecase (Manage Invoice) as (usecaseInvoice)
    usecase (View Invoice) as (usecaseViewInvoice)
    usecase (Create Invoice) as (usecaseCreateInvoice)
    usecase (Edit Invoice) as (usecaseEditInvoice)
    usecase (Print Invoice) as (usecasePrintInvoice)

    ' ================ Product ================
    '    การสั่งซื้อสินค้า
    usecase (product) as (usecaseProduct)
    usecase (View product) as (usecaseViewProduct)

    usecase (Add product) as (usecaseAddProduct)
    usecase (update product) as (usecaseUpdateProduct)
    usecase (Delete product) as (usecaseDeleteProduct)

    usecase (Pick up product) as (usecasePickUpProduct)

    ' ================ Stock ================
    usecase (Inventory) as (usecaseInventory)
    usecase (Check Stock) as (usecaseCheckStock)
    usecase (Add stock) as (usecaseAddStock)
    usecase (Update stock) as (usecaseUpdateStock)

    ' ================ Shipment ================
    usecase (Shipment) as (usecaseShipment)


    '===========================================================
    ' ===                  Associate Flow                    ===
    '===========================================================


   ' ================ Product ================
       actorManager -- (usecaseViewProduct)
    (usecaseProduct) <.. (usecaseAddProduct)  : <<extends>>
    (usecaseUpdateProduct) ..> (usecaseProduct) : <<extends>>
    (usecaseProduct) <.. (usecaseDeleteProduct)  : <<extends>>
    (usecasePickUpProduct) ..> (usecaseProduct) : <<extends>>
    (usecaseProduct) <.. (usecaseViewProduct) : <<extends>>

    ' ================ Stock ================
     actorSupplier -down- (usecaseShipment)
        (usecaseInventory) - actorManager



    (usecaseAddStock) ..> (usecaseCheckStock) : <<extends>>
    (usecaseAddStock) ..> (usecaseViewProduct) : <<include>>
    (usecaseUpdateStock) ..> (usecaseInventory) : <<extends>>
    (usecaseInventory) <.. (usecaseCheckStock) : <<extends>>

    ' ================ Sell ================
    (usecaseSellProduct) ..> (usecaseSell) : <<extends>>
    (usecaseCheckStock) <.. (usecaseSell)    : <<include>>

    (usecaseSellProduct)  ..> (usecaseCreateReceipt) : <<include>>

   '   ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการขาย
    actorSalesperson -- (usecaseSell)


    '   การลงรับสินค้า เป็นส่วนหนึ่งของกระบวนการสั่งซื้อสินค้า
    (usecaseOrder) ..> (usecasePickUpProduct) : <<include>>

    '   การปรับปรุงยอดสินค้า เป็นส่วนหนึ่งของกระบวนการสั่งซื้อสินค้า
    (usecaseCheckStock) <.. (usecaseOrder) : <<include>>

    ' ================ Order ================
    (usecaseOrder) <.. (usecaseDeleteOrder) : <<extends>>
    (usecaseEditOrder) ..> (usecaseOrder) : <<extends>>
    (usecaseEditOrder) ..> (usecaseUpdateStock) : <<include>>
    (usecaseDeleteOrder) ..> (usecaseUpdateStock) : <<include>>
    (usecaseCreateInvoice) <.. (usecaseOrder) : <<include>>

    ' ===  ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการสั่งซื้อสินค้า ===
    actorSalesperson -- (usecaseOrder)
    (usecaseOrder) -- actorCustomer


    ' ================ Invoice ================
    (usecaseInvoice) <.. (usecaseViewInvoice) : <<extends>>
    (usecaseInvoice)  <..   (usecaseCreateInvoice): <<extends>>
    (usecaseEditInvoice) ..> (usecaseInvoice) : <<extends>>

    (usecaseCreateInvoice) ..> (usecasePrintInvoice) : <<uses>>
    (usecasePrintInvoice) ..> (usecaseViewInvoice) : <<uses>>

    ' ================ Receipt ================
    (usecaseCreateReceipt) .up.> (usecaseReceipt) : <<extends>>
    (usecaseViewReceipt) ..> (usecaseReceipt) : <<extends>>
    (usecaseEditReceipt) ..> (usecaseReceipt) : <<extends>>

    (usecaseCreateReceipt) .up.> (usecasePrintReceipt) : <<uses>>
    (usecaseViewReceipt)  <..   (usecasePrintReceipt): <<uses>>


    ' ===  ความสัมพันธ์ระหว่าง actor และ usecase ในส่วนของการสออกรายงาน ===
    actorManager -- (usecaseSellReport)
    actorFinancial -right- (usecaseSellReport)


    ' ================ Reporting ================
    '   การทำรายงาน

    (usecaseViewInvoice) <..  (usecaseSellReport)   : <<include>>
    (usecaseSellReport) ..> (usecaseViewReceipt)    : <<include>>
    (usecaseCheckStock)  <.. (usecaseSellReport)  : <<include>>
    (usecaseListProductForStock) <..  (usecaseSellReport)   : <<extends>>

    (usecaseViewProduct) <... (usecaseListProductForStock) : <<include>>

    (usecaseListProductForStock) ..>  (usecaseOrder)   : <<include>>
'    actorCEO -- (usecaseListProductForStock)

    note "ยืนยันคำสั่งซื้อ" as ListOrderForStock
    actorCEO -- ListOrderForStock
    ListOrderForStock -- (usecaseListProductForStock)

    ' ================ Shipment ================

}

@enduml